"use client";
import {useSiteContent} from './SiteContentProvider';
import {useEffect,useRef,useState} from 'react';import dynamic from 'next/dynamic';
const HeroThree=dynamic(()=>import('./HeroThree'),{ssr:false});
const ROLES:Record<string,{label:string;phrases:string[]}>={
 dev:{label:'⌘ Developer',phrases:['I build products.','I ship AI apps.','I write code.']},design:{label:'✦ Designer',phrases:['I design brands.','I craft identity.','I shape systems.']},it:{label:'⛨ IT & Security',phrases:['I secure networks.','I run infrastructure.','I connect teams.']},data:{label:'◈ Data Scientist',phrases:['I model data.','I find the signal.','IBM-certified.']}
};const ORDER=['dev','design','it','data'];
function Counter({to,suffix=''}:{to:number;suffix?:string}){const ref=useRef<HTMLElement>(null);useEffect(()=>{const el=ref.current;if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const io=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;io.disconnect();const start=performance.now();function step(now:number){const k=Math.min(1,(now-start)/1400);if(el)el.textContent=Math.round(to*(1-Math.pow(1-k,3)))+suffix;if(k<1)frame=requestAnimationFrame(step);}frame=requestAnimationFrame(step);},{threshold:.6});io.observe(el);return()=>{io.disconnect();cancelAnimationFrame(frame);};},[to,suffix]);return <em ref={ref}>{to}{suffix}</em>;}
export default function Hero(){const site=useSiteContent();const [role,setRole]=useState('dev'),[text,setText]=useState(ROLES.dev.phrases[0]),[paused,setPaused]=useState(false);const roleRef=useRef('dev');const interacted=useRef(false);
useEffect(()=>{document.documentElement.dataset.motion=paused?'paused':'running';},[paused]);
useEffect(()=>{roleRef.current=role;document.documentElement.dataset.role=role;const phrases=ROLES[role].phrases;if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches){setText(phrases[0]);return;}let pi=0,ci=0,del=false,timer:ReturnType<typeof setTimeout>;function loop(){const word=phrases[pi%phrases.length];ci+=del?-1:1;setText(word.slice(0,ci));let delay=del?28:55;if(ci===word.length){del=true;delay=1900;}else if(ci===0){del=false;pi++;delay=300;}timer=setTimeout(loop,delay);}loop();return()=>clearTimeout(timer);},[role,paused]);
useEffect(()=>{if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let i=0;const timer=setInterval(()=>{if(!interacted.current&&!document.hidden){i=(i+1)%ORDER.length;setRole(ORDER[i]);}},6000);return()=>clearInterval(timer);},[paused]);
return <section id="hero"><HeroThree roleRef={roleRef} paused={paused}/><div className="wrap hero-inner"><span className="eyebrow">{site.tagline}</span><h1>{site.name}</h1><div className="role-line" aria-hidden="true"><span>{text}</span><span className={paused?'caret paused':'caret'}/></div><span className="sr-only">Developer, designer, IT and security professional, and data scientist.</span><p className="hero-sub">{site.bio}</p><div className="role-tabs" role="group" aria-label="Explore my four work areas">{ORDER.map(r=><button key={r} className={'role-tab'+(role===r?' active':'')} aria-pressed={role===r} onClick={()=>{interacted.current=true;setRole(r);}}>{ROLES[r].label}</button>)}</div><div className="hero-cta"><a className="btn solid" href="#works">View my work →</a><a className="btn ghost" href="#contact">Let’s talk</a><button className="motion-toggle" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Resume motion':'Pause motion'}</button></div><div className="hero-stats">{site.stats.map(([value,label])=><div className="hstat" key={label}><b><Counter to={parseFloat(value)||0} suffix={value.replace(/[0-9.]/g,'')}/></b><span>{label}</span></div>)}</div></div><a className="scroll-hint" href="#about">Scroll<i/></a></section>;
}