"use client";
import {useSiteContent} from "./SiteContentProvider";
import Link from 'next/link';import Reveal from './Reveal';import ProjectVisual from './ProjectVisual';import type {Project} from '@/lib/catalog';
export function About(){const site=useSiteContent();const tracks=useSiteContent().tracks;return <section id="about" className="alt-bg"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Who I am</span><h2>{site.aboutTitle}</h2><p>{site.about}</p></div></Reveal><div className="tracks">{tracks.map((tk,i)=><Reveal key={tk.t} delay={(i%3)*.08}><article className="track" style={{'--tk':tk.c} as React.CSSProperties}><div className="ico" aria-hidden="true">{tk.icon}</div><h3>{tk.t}</h3><p>{tk.d}</p><ul>{tk.li.map(x=><li key={x}>{x}</li>)}</ul></article></Reveal>)}</div><Reveal><div className="metrics">{site.metrics.map(([b,s])=><div className="metric" key={s}><b>{b}</b><span>{s}</span></div>)}</div></Reveal></div></section>;}
export function Marquee(){const items=useSiteContent().marquee;return <div className="marquee" aria-label="Technology stack"><div className="inner" aria-hidden="true">{[0,1].map(n=><span key={n}>{items.map(x=><span key={x}>{x} <b>✦</b> </span>)}</span>)}</div><span className="sr-only">{items.join(', ')}</span></div>;}
export function Services(){const svc=useSiteContent().services;return <section id="services"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Services</span><h2>What I can do <span className="tint">for you</span></h2></div></Reveal><div className="svc-grid">{svc.map(([n,h,p,service],i)=><Reveal key={n} delay={(i%3)*.05}><Link className="svc" href={'/contact?service='+encodeURIComponent(service)}><span className="n">{n}</span><span className="go">↗</span><h3>{h}</h3><p>{p}</p></Link></Reveal>)}</div></div></section>;}
export function Skills(){const cols=useSiteContent().skills;return <section id="skills" className="alt-bg"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Stack</span><h2>Tools I <span className="tint">work with</span></h2></div></Reveal><div className="skill-cols">{cols.map(([h,list],i)=><Reveal key={h} delay={(i%3)*.05}><div className="skill-card"><h3>{h}</h3><div className="chips">{list.map(c=><span className="chip" key={c}>{c}</span>)}</div></div></Reveal>)}</div></div></section>;}
export function CropWise({project}:{project?:Project}){if(!project)return null;return <section id="cropwise"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Featured product</span><h2>{project.title}</h2><p>{project.description}</p></div></Reveal><div className="spot"><Reveal><div className="body"><p>{project.challenge}</p><p>{project.solution}</p><div className="scr-tags">{project.tech.split(',').filter(Boolean).map(t=><i key={t}>{t}</i>)}</div><div className="hero-cta"><Link className="btn solid" href={'/work/'+project.slug}>Explore the project →</Link>{project.liveUrl&&<a className="btn ghost" href={project.liveUrl} target="_blank" rel="noopener noreferrer">View live project ↗</a>}<Link className="btn ghost" href="/contact?service=Development">Want an app like this?</Link></div></div></Reveal><Reveal delay={.15}><ProjectVisual project={project}/></Reveal></div></div></section>;}
export function Experience(){const main=useSiteContent().experience;
const freelance=useSiteContent().freelance;
return <section id="experience" className="alt-bg"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Journey</span><h2>Where I’ve <span className="tint">delivered</span></h2></div></Reveal><div className="timeline">{main.map(([when,title,org,body,tags])=><Reveal key={title}><div className="tl-item"><span className="when">{when}</span><h3>{title}</h3><div className="org">{org}</div><p>{body}</p><div className="tags">{tags.split(',').map(t=><i key={t}>{t}</i>)}</div></div></Reveal>)}<p className="tl-sub">— Selected freelance work · Canada / UAE / India —</p>{freelance.map(([when,title,body])=><Reveal key={title}><div className="tl-item"><span className="when">{when}</span><h3>{title}</h3><p>{body}</p></div></Reveal>)}</div></div></section>;}
export function Education(){const edu=useSiteContent().education;const certs=useSiteContent().certifications;return <section id="education"><div className="wrap"><Reveal><div className="sec-head"><span className="eyebrow">Foundation</span><h2>Education & <span className="tint">certifications</span></h2></div></Reveal><div className="edu-grid">{edu.map(([w,h,p],i)=><Reveal key={h} delay={(i%2)*.05}><div className="edu"><span className="when">{w}</span><h3>{h}</h3><p>{p}</p></div></Reveal>)}</div><div className="cert-grid">{certs.map(([b,s])=><Reveal key={b}><div className="cert"><span className="dot"/><div><b>{b}</b><span>{s}</span></div></div></Reveal>)}</div></div></section>;}
export function Footer(){const site=useSiteContent();return <footer><div className="wrap footer-inner"><p>© {new Date().getFullYear()} {site.name} — {site.footer}</p><div className="footer-links"><Link href="/privacy">Privacy</Link><Link href="/admin">Admin</Link><div className="socials"><a href={site.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">in</a><a href={site.github} target="_blank" rel="noopener noreferrer" aria-label="GitHub">⌘</a><a href={site.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram">◎</a></div></div></div></footer>;}
