"use client";
import GoogleCaptcha,{getCaptchaToken} from './GoogleCaptcha';
import {useCallback,useEffect,useRef,useState} from 'react';import {usePathname} from 'next/navigation';
type Message={id:string;sender:string;body:string;createdAt:string};type Conversation={firstName:string;lastName:string;email:string;status:string;unreadVisitor:number;messages:Message[]};type Presence={online:boolean;hours:string};
export default function SupportChat(){const path=usePathname();const [open,setOpen]=useState(false),[conversation,setConversation]=useState<Conversation|null>(null),[presence,setPresence]=useState<Presence>({online:false,hours:'Monday–Friday, 9:00 AM–6:00 PM GST'}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const end=useRef<HTMLDivElement>(null);
 const token=useRef('');useEffect(()=>{token.current=localStorage.getItem('cs-support-token')||crypto.randomUUID();localStorage.setItem('cs-support-token',token.current);},[]);
 const load=useCallback(async()=>{if(!token.current)return;try{const r=await fetch('/api/support?token='+encodeURIComponent(token.current),{cache:'no-store'}),j=await r.json();if(r.ok){setPresence(j.presence);setConversation(j.conversation);}}catch{}},[]);
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id);},[load]);useEffect(()=>{if(open)end.current?.scrollIntoView({behavior:'smooth'});},[open,conversation]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const submittedForm=e.currentTarget;setBusy(true);setError('');const form=new FormData(e.currentTarget);const payload=conversation?{action:'message',token:token.current,message}:{action:'start',token:token.current,firstName:form.get('firstName'),lastName:form.get('lastName'),email:form.get('email'),message:form.get('message'),website:form.get('website')};try{const captchaToken=await getCaptchaToken('support');const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,captchaToken})}),j=await r.json();if(!r.ok)throw Error(j.error);setConversation(j.conversation);setPresence(j.presence);setMessage('');submittedForm.reset();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(path.startsWith('/admin'))return null;return <aside className={'support-widget '+(open?'is-open':'')} aria-label="Support chat"><button className="support-launch" type="button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><span className={presence.online?'support-dot online':'support-dot'}/><span>{open?'Close':'Support'}</span>{conversation?.unreadVisitor? <b>{conversation.unreadVisitor}</b>:null}</button>{open&&<section className={'support-panel '+(conversation?'has-conversation':'is-starting')} aria-label="Support conversation"><header><div><strong>{presence.online?'Chat with Charanjit':'Leave a message'}</strong><small>{presence.online?'Available now · Usually replies shortly':presence.hours}</small></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close support">×</button></header>{conversation?<><div className="support-messages" aria-live="polite">{conversation.messages.map(m=><div key={m.id} className={'support-message '+m.sender}><span>{m.sender==='admin'?'Charanjit':'You'}</span><p>{m.body}</p><time>{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>)}{conversation.status==='closed'&&<p className="support-closed">This conversation is closed. Sending a message will reopen it.</p>}<div ref={end}/></div><form onSubmit={submit} className="support-reply"><label className="sr-only" htmlFor="support-message">Message</label><textarea id="support-message" required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write your message…"/><GoogleCaptcha/><button disabled={busy||!message.trim()}>{busy?'Sending…':'Send ↗'}</button></form></>:<form onSubmit={submit} className="support-start"><p>Tell me what you need, and I’ll reply here.</p><div><label>First name<input name="firstName" required maxLength={80} autoComplete="given-name" placeholder="First name"/></label><label>Last name<input name="lastName" required maxLength={80} autoComplete="family-name" placeholder="Last name"/></label></div><label>Email<input name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.com"/></label><label>How can I help?<textarea name="message" required minLength={2} maxLength={4000} placeholder="Tell me about your project or question…"/></label><input className="support-trap" name="website" tabIndex={-1} autoComplete="off"/><GoogleCaptcha/><button disabled={busy}>{busy?'Starting…':'Start conversation ↗'}</button></form>}{error&&<p className="support-error" role="alert">{error}</p>}<footer>Private support · UAE time (GST)</footer></section>}</aside>}
