import 'server-only';
import {randomBytes,randomInt,createHash,createHmac,timingSafeEqual,createCipheriv,createDecipheriv,randomUUID} from 'crypto';
import bcrypt from 'bcryptjs';import {state,activity} from './platform-state';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
function key(){if(!process.env.AUTH_SECRET||process.env.AUTH_SECRET.length<32)throw Error('Missing authentication secret');return createHash('sha256').update(process.env.AUTH_SECRET).digest();}
function encrypt(s:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([cipher.update(s,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64');}
function decrypt(s:string){const b=Buffer.from(s,'base64');const decipher=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));decipher.setAuthTag(b.subarray(12,28));return Buffer.concat([decipher.update(b.subarray(28)),decipher.final()]).toString('utf8');}
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32(b:Buffer){let bits='';for(const n of b)bits+=n.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5)out+=alphabet[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out;}
function decode(s:string){let bits='';for(const c of s)bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');return Buffer.from((bits.match(/.{8}/g)||[]).map(b=>parseInt(b,2)));}
export function otp(secret:string,step:number,digits=6){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(step));const h=createHmac('sha1',decode(secret)).update(b).digest();const n=h[h.length-1]&15;return String((h.readUInt32BE(n)&0x7fffffff)%10**digits).padStart(digits,'0');}
function match(secret:string,code:string,last=-1){if(!/^\d{6}$/.test(code))return -1;const step=Math.floor(Date.now()/30000);for(const offset of [0,-1,1]){const n=step+offset;if(n>last&&timingSafeEqual(Buffer.from(otp(secret,n)),Buffer.from(code)))return n;}return -1;}
export async function verifySecondFactor(code:string){return state(s=>{const sec=s.security;if(!sec.totp)return true;const step=match(decrypt(sec.totp),code,sec.lastStep);if(step>=0){sec.lastStep=step;return true;}const index=sec.recovery.indexOf(hash(code.replace(/\s/g,'')));if(index<0)return false;sec.recovery.splice(index,1);activity(s,'A recovery code was used to sign in');return true;},true);}
export async function startEnrollment(){const secret=base32(randomBytes(20));await state(s=>{if(s.security.totp)throw Error('Two-factor authentication is already enabled.');s.security.pendingTotp=encrypt(secret);s.security.pendingUntil=Date.now()+600000;},true);return {secret,uri:'otpauth://totp/Portfolio:'+encodeURIComponent(process.env.ADMIN_EMAIL||'Admin')+'?secret='+secret+'&issuer=Portfolio&algorithm=SHA1&digits=6&period=30'};}
export async function confirmEnrollment(code:string){return state(s=>{const sec=s.security;if(!sec.pendingTotp||!sec.pendingUntil||sec.pendingUntil<Date.now())throw Error('Start setup again.');const step=match(decrypt(sec.pendingTotp),code);if(step<0)throw Error('Invalid authenticator code.');const codes=Array.from({length:8},()=>randomBytes(8).toString('hex'));sec.totp=sec.pendingTotp;sec.lastStep=step;delete sec.pendingTotp;delete sec.pendingUntil;sec.recovery=codes.map(hash);sec.sessions=[];activity(s,'Two-factor authentication enabled; all sessions revoked');return codes;},true);}
export async function newSession(agent:string){const id=randomUUID();await state(s=>{s.security.sessions=s.security.sessions.filter(x=>x.expires>Date.now()).slice(-19);s.security.sessions.push({id,agent:agent.slice(0,160),createdAt:Date.now(),expires:Date.now()+43200000});activity(s,'Admin signed in');},true);return id;}
export const sessionActive=(id:string)=>state(s=>s.security.sessions.some(x=>x.id===id&&x.expires>Date.now()));
const resetCodeHash=(code:string)=>createHmac('sha256',key()).update('admin-password-reset:'+code).digest('hex');
export async function requestResetCode(){const code=String(randomInt(0,100000000)).padStart(8,'0');await state(s=>{s.security.reset={hash:resetCodeHash(code),expires:Date.now()+600000,attempts:0};},true);return code;}
export async function resetPassword(code:string,password:string){const passwordHash=await bcrypt.hash(password,12);const result=await state(s=>{const reset=s.security.reset;if(!reset||reset.expires<Date.now()||(reset.attempts||0)>=5)return false;const expected=Buffer.from(reset.hash,'hex'),actual=Buffer.from(resetCodeHash(code),'hex');if(expected.length!==actual.length||!timingSafeEqual(expected,actual)){reset.attempts=(reset.attempts||0)+1;return false;}s.security.passwordHash=passwordHash;s.security.sessions=[];delete s.security.reset;activity(s,'Password reset with email code; all sessions revoked');return true;},true);if(!result)throw Error('Invalid or expired email code. Request a new code if needed.');}
