import legacy from './legacy-projects.json';
import {projectEditorial} from './project-editorial';
export const disciplines = [
  { id: 'web', number: '01', name: 'Development', verb: 'Make it work.', subtitle: 'Websites, applications & AI', description: 'From a useful idea to a product people can actually use. Thoughtful interfaces, dependable engineering, and AI with a purpose.', tools: 'Next.js · React · Laravel · Android · AI', color: 'blue' },
  { id: 'design', number: '02', name: 'Design', verb: 'Make it felt.', subtitle: 'Identity, digital & print', description: 'A clear identity, a considered experience, a detail you remember. Design that connects a business to the people it serves.', tools: 'Brand identity · UI/UX · Packaging · Motion', color: 'orange' },
  { id: 'data', number: '03', name: 'Data science', verb: 'Find the meaning.', subtitle: 'Analysis, insight & growth', description: 'Turn complexity into clarity. Connect data, analytics, and digital marketing to better decisions and measurable progress.', tools: 'Python · SQL · R · Analytics · SEO', color: 'green' },
  { id: 'it', number: '04', name: 'IT & security', verb: 'Keep it connected.', subtitle: 'Infrastructure & resilience', description: 'The foundation behind the experience. Connected teams, reliable infrastructure, and carefully managed systems.', tools: 'Microsoft 365 · Entra ID · FortiGate · Cloud', color: 'purple' },
] as const;
export type Category = 'web' | 'design' | 'data' | 'it' | 'app' | 'other';
export type Project = {
  videoUrl?:string;documentUrl?:string;seoTitle?:string;seoDescription?:string;socialImage?:string;results?:string;deleted?:boolean; id: number; title: string; slug: string; category: Category; description: string; coverImage: string;
  coverAlt: string; liveUrl: string | null; repoUrl: string | null; tech: string; year: string;
  featured: boolean; published: boolean; order: number; client: string; role: string;
  challenge: string; solution: string; outcome: string; gallery: string[];
};
export const catalog: Project[] = legacy.map((p, i) => ({
  ...p, id: i + 1, category: p.category as Category, coverImage: p.coverImage.replace('https://thecharanjitsingh.com', 'https://www.thecharanjitsingh.com'),
  coverAlt: p.title + ' — project presentation', liveUrl: p.liveUrl.includes('thecharanjitsingh.com') ? null : p.liveUrl,
  repoUrl: null, featured: i < 2, published: true, client: p.title.startsWith('RNZ') ? 'RNZ Group' : p.title.startsWith('Expocrop') ? 'Expocrop' : p.title.startsWith('Ajooba') ? 'Ajooba' : p.title,
  role: p.category === 'design' ? 'Brand & visual designer' : 'Developer & digital experience designer',
  challenge: p.category === 'design' ? 'Translate a business and its products into a clear visual language across customer touchpoints.' : 'Create a useful digital presence that makes information easier to discover and the business easier to engage with.',
  solution: p.description, outcome: p.category === 'design' ? 'A coordinated collection of brand assets for digital and physical use.' : 'A delivered web experience, supported by the technologies and responsibilities listed below.', gallery: [],
}));
catalog.unshift({ id: 11, title: 'Agri Cropwise', slug: 'agri-cropwise', category: 'app', description: 'An agricultural product ecosystem, brought together in an AI-powered Android app.', coverImage: '', coverAlt: 'Agri Cropwise — illustrated project cover', liveUrl: null, repoUrl: null, tech: 'Android,AI,Firebase,RAG', year: '2026', featured: true, published: true, order: 0, client: 'Agri Cropwise', role: 'Product design & full-stack development', challenge: 'Bring product discovery, crop advice, and supporting information into one accessible mobile experience.', solution: 'Designed and built an Android application with a filterable catalogue, AI crop advisor, source-grounded chat, favourites, brochures, and an administration console.', outcome: 'A connected product experience spanning the customer-facing application and the tools used to manage its content. ', gallery: [] });
catalog.push({ id: 12, title: 'Hindi Quran Viewer', slug: 'hindi-quran-viewer-plugin', category: 'web', description: 'A WordPress plugin for presenting Quranic verses in Hindi with English translation.', coverImage: '', coverAlt: 'Hindi Quran Viewer typographic project cover', liveUrl: null, repoUrl: null, tech: 'WordPress,PHP,Shortcodes', year: '', featured: false, published: true, order: 12, client: 'Independent project', role: 'Plugin developer', challenge: 'Make multilingual reading content accessible within an existing WordPress website.', solution: 'A shortcode-based plugin that brings Hindi verses and English translation into a customizable presentation.', outcome: 'A reusable WordPress integration. ', gallery: [] });
catalog.push(...[
 {id:13,title:'iapply.io — Unified Search',slug:'iapply-unified-search',year:'2020–2021',client:'iapply.io',tech:'SPA,APIs,Authentication',description:'A responsive application connecting multiple data types through one search and a unified login.',role:'Lead full-stack developer',challenge:'Bring multiple sources of information into a consistent, responsive search experience.',solution:'Built a single-page application with a unified login and search across different data types.',outcome:'A unified application workflow, delivered as part of a freelance development engagement.'},
 {id:14,title:'Nav — Recognition & Automation',slug:'nav-recognition-automation',year:'2020',client:'Nav',tech:'Django,Vue,APIs,Automation',description:'An image-recognition application and data ingestion workflows built with Django and Vue.',role:'Lead web-application developer',challenge:'Support image recognition and large-scale information processing with practical application workflows.',solution:'Developed a Django and Vue application, data ingestion APIs for risk modelling, and automation tools.',outcome:'Connected application and automation workflows that reduced repetitive processing work.'},
 {id:15,title:'Sanskriti Bazaar',slug:'sanskriti-bazaar',year:'2019',client:'Sanskriti Bazaar',tech:'Angular,Frontend,Testing',description:'Frontend development, performance improvements, and broader test coverage for an e-commerce experience.',role:'Senior full-stack developer',challenge:'Improve the experience and reliability of an existing commerce application.',solution:'Built Angular components, improved page performance, and expanded automated test coverage.',outcome:'An improved frontend and stronger regression coverage for the commerce platform.'},
].map(p=>({...p,category:'web' as const,coverImage:'',coverAlt:p.title+' — project cover',liveUrl:null,repoUrl:null,featured:false,published:true,order:p.id,gallery:[]})));
for (const project of catalog) { project.coverImage = '/work/covers/' + project.slug + '.svg'; project.coverAlt = project.title + ' — illustrated project cover'; }
for (const project of catalog) Object.assign(project, projectEditorial[project.slug] || {});
export const categoryLabel = (category: string) => ({ web: 'Development', app: 'AI & mobile', design: 'Brand & design', data: 'Data science', it: 'IT & security', other: 'Other work' }[category] || category);
export const aliases: Record<string, string> = { 'rnz-cropwise': 'agri-cropwise', 'rnz-group-website-design': 'rnz-group-website', 'expocrop-website-design': 'expocrop-website', 'expocrop-logo-design': 'expocrop-logo-branding', 'ajooba-llc-website-design': 'ajooba-llc-website', 'ajooba-ae-website-design': 'ajooba-ae-opencart', 'ajooballc-gift-item-designs': 'ajooba-gift-item-designs', 'kalia-law-firm-website-design': 'kalia-law-firm', 'forexamg-website-development': 'forexamg-platform' };
