import 'server-only';import {promises as fs} from 'fs';import path from 'path';import {randomUUID} from 'crypto';import {prisma} from './prisma';import {hasDatabase,localEnabled} from './store';
export type ManagedSite={id:string;clientName:string;label:string;url:string;domainCharge:number|null;serverCharge:number|null;domainProvider:string;domainRenewal:string|null;serverProvider:string;serverRenewal:string|null;contactEmail:string;notes:string;active:boolean;lastStatus:number|null;lastResponseMs:number|null;lastPerformance:number|null;lastSeo:number|null;lastAccessibility:number|null;lastBestPractices:number|null;lastCheckedAt:string|null;reminderLog:Record<string,string>;createdAt:string;updatedAt:string;audits:SiteAudit[]};export type SiteAudit={id:string;managedSiteId:string;status:number|null;responseMs:number|null;performance:number|null;seo:number|null;accessibility:number|null;bestPractices:number|null;issues:string[];createdAt:string};
type Local={sites:ManagedSite[]};const file=path.join(process.cwd(),process.env.LOCAL_DATA_DIR||'.data','managed-sites.json');let queue:Promise<unknown>=Promise.resolve();async function local<T>(fn:(d:Local)=>T|Promise<T>,write=false){if(!localEnabled())throw Error('Database is not configured.');const op=queue.then(async()=>{let d:Local;try{d=JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;d={sites:[]};}const out=await fn(d);if(write){await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.tmp';await fs.writeFile(temp,JSON.stringify(d,null,2));await fs.rename(temp,file);}return out;});queue=op.catch(()=>{});return op;}
type AuditSource=Omit<SiteAudit,'createdAt'|'issues'>&{createdAt:Date|string;issues:unknown};type SiteSource=Omit<ManagedSite,'domainCharge'|'serverCharge'|'domainRenewal'|'serverRenewal'|'lastCheckedAt'|'createdAt'|'updatedAt'|'reminderLog'|'audits'>&{domainCharge:unknown;serverCharge:unknown;domainRenewal:Date|string|null;serverRenewal:Date|string|null;lastCheckedAt:Date|string|null;createdAt:Date|string;updatedAt:Date|string;reminderLog:unknown;audits:AuditSource[]};
const date=(v:Date|string|null)=>v?new Date(v).toISOString():null;const row=(x:SiteSource):ManagedSite=>({...x,domainCharge:x.domainCharge==null?null:Number(x.domainCharge),serverCharge:x.serverCharge==null?null:Number(x.serverCharge),domainRenewal:date(x.domainRenewal),serverRenewal:date(x.serverRenewal),lastCheckedAt:date(x.lastCheckedAt),createdAt:new Date(x.createdAt).toISOString(),updatedAt:new Date(x.updatedAt).toISOString(),reminderLog:(x.reminderLog&&typeof x.reminderLog==='object'?x.reminderLog:{}) as Record<string,string>,audits:x.audits.map(a=>({...a,issues:Array.isArray(a.issues)?a.issues.filter((v):v is string=>typeof v==='string'):[],createdAt:new Date(a.createdAt).toISOString()}))});
export async function listManagedSites(){if(hasDatabase())return (await prisma.managedSite.findMany({include:{audits:{orderBy:{createdAt:'desc'},take:10}},orderBy:[{active:'desc'},{updatedAt:'desc'}]})).map(row);return local(d=>d.sites.map(x=>({...x,domainCharge:x.domainCharge??null,serverCharge:x.serverCharge??null})));}
export async function getManagedSite(id:string){if(hasDatabase()){const x=await prisma.managedSite.findUnique({where:{id},include:{audits:{orderBy:{createdAt:'desc'},take:10}}});return x?row(x):null;}return local(d=>d.sites.find(x=>x.id===id)||null);}
type Input=Pick<ManagedSite,'domainCharge'|'serverCharge'|'clientName'|'label'|'url'|'domainProvider'|'domainRenewal'|'serverProvider'|'serverRenewal'|'contactEmail'|'notes'|'active'>;
export async function saveManagedSite(input:Input,id?:string){const data={...input,domainRenewal:input.domainRenewal?new Date(input.domainRenewal):null,serverRenewal:input.serverRenewal?new Date(input.serverRenewal):null};if(hasDatabase())return row(id?await prisma.managedSite.update({where:{id},data,include:{audits:true}}):await prisma.managedSite.create({data:{...data,reminderLog:{}},include:{audits:true}}));return local(d=>{const now=new Date().toISOString();if(id){const i=d.sites.findIndex(x=>x.id===id);if(i<0)throw Error('Managed website not found.');d.sites[i]={...d.sites[i],...input,updatedAt:now};return d.sites[i];}const x:ManagedSite={...input,id:randomUUID(),lastStatus:null,lastResponseMs:null,lastPerformance:null,lastSeo:null,lastAccessibility:null,lastBestPractices:null,lastCheckedAt:null,reminderLog:{},createdAt:now,updatedAt:now,audits:[]};d.sites.unshift(x);return x;},true);}
export async function deleteManagedSite(id:string){if(hasDatabase()){await prisma.managedSite.delete({where:{id}});return;}return local(d=>{d.sites=d.sites.filter(x=>x.id!==id);},true);}
export async function saveAudit(id:string,a:Omit<SiteAudit,'id'|'managedSiteId'|'createdAt'>){const now=new Date();if(hasDatabase()){await prisma.$transaction([prisma.siteAudit.create({data:{managedSiteId:id,...a,issues:a.issues}}),prisma.managedSite.update({where:{id},data:{lastStatus:a.status,lastResponseMs:a.responseMs,lastPerformance:a.performance,lastSeo:a.seo,lastAccessibility:a.accessibility,lastBestPractices:a.bestPractices,lastCheckedAt:now}})]);return;}return local(d=>{const x=d.sites.find(s=>s.id===id);if(!x)throw Error('Managed website not found.');const audit={...a,id:randomUUID(),managedSiteId:id,createdAt:now.toISOString()};x.audits.unshift(audit);x.audits=x.audits.slice(0,10);Object.assign(x,{lastStatus:a.status,lastResponseMs:a.responseMs,lastPerformance:a.performance,lastSeo:a.seo,lastAccessibility:a.accessibility,lastBestPractices:a.bestPractices,lastCheckedAt:now.toISOString(),updatedAt:now.toISOString()});},true);}
export async function setReminderLog(id:string,log:Record<string,string>){if(hasDatabase()){await prisma.managedSite.update({where:{id},data:{reminderLog:log}});return;}return local(d=>{const x=d.sites.find(s=>s.id===id);if(x)x.reminderLog=log;},true);}
