import type {Project} from './catalog';

type Editorial = Partial<Pick<Project, 'description'|'coverImage'|'coverAlt'|'client'|'role'|'challenge'|'solution'|'outcome'|'tech'|'liveUrl'|'seoTitle'|'seoDescription'|'socialImage'>>;

// User-confirmed contributions, supported by the linked live sites. Measured outcomes are omitted until supplied.
export const projectEditorial: Record<string, Editorial> = {
  'kalia-law-firm': {
    description: 'WordPress website for a Brampton law firm, presenting family law, real estate, wills and other services with clear routes to contact.',
    coverImage: '/work/kalia-live-shot.gif',
    coverAlt: 'Screenshot of the Kalia Law Firm website showing its navigation, legal services and homepage hero',
    socialImage: '/work/kalia-live-shot.gif',
    client: 'Kalia Law Firm',
    role: 'WordPress developer · SEO · social media setup',
    challenge: 'Present a broad legal practice clearly for prospective clients in Brampton and surrounding Ontario communities, making services and contact information easy to find.',
    solution: 'I built the WordPress website and organised the firm’s practice areas into service-led pages and clear enquiry paths. I also worked on the site’s SEO and created its social media presence. The live site covers family law, real estate, wills and estates, notary services and other legal needs.',
    outcome: 'A live, service-led online presence that helps visitors understand the firm’s practice areas and get in touch for a consultation.',
    tech: 'WordPress,Web Design,On-page SEO,Local SEO,Social Media',
    liveUrl: 'https://www.kalialaw.com/',
    seoTitle: 'Kalia Law Firm WordPress Website & SEO | Charanjit Singh',
    seoDescription: 'Explore the WordPress website Charanjit Singh built for Kalia Law Firm in Brampton, including service-led design, SEO work and social media setup.',
  },
  'rnz-group-website': {
    description: 'WordPress corporate website for a global crop-nutrition group, connecting company divisions, product categories, news and enquiries.',
    client: 'RNZ Group',
    role: 'In-house WordPress developer · SEO · digital design',
    challenge: 'Bring the group’s companies, crop-nutrition expertise and broad product range into one clear website for an international audience.',
    solution: 'As part of RNZ Group, I built and continue to work on its WordPress website. I structured the corporate and product information, supported content and design updates, and worked on the site’s SEO and social media presence.',
    outcome: 'The live website brings together RNZ Group’s divisions, crop-nutrition solutions, product categories, news and contact routes in one digital presence.',
    tech: 'WordPress,Web Design,Technical SEO,Content Strategy,Social Media',
    liveUrl: 'https://rnz-group.com/',
    seoTitle: 'RNZ Group WordPress Website & SEO | Charanjit Singh',
    seoDescription: 'A case study of Charanjit Singh’s in-house WordPress development, SEO and digital design work for RNZ Group’s crop-nutrition website.',
  },
  'rnz-group-design-portfolio': {
    description: 'An evolving RNZ Group design collection: product brochures, exhibition standees, fertilizer bags, bottle labels and social creatives.',
    client: 'RNZ Group',
    role: 'In-house brand and graphic designer',
    challenge: 'Create a consistent visual language across product communication, packaging, events and social channels for a multi-entity agriculture group.',
    solution: 'I design product brochures, exhibition standees, fertilizer bag graphics, bottle labels and digital/social assets for RNZ Group, carrying the brand’s visual language across physical and online materials.',
    outcome: 'A coordinated set of print, packaging, exhibition and digital designs that helps RNZ Group present its products consistently across touchpoints.',
    tech: 'Adobe Illustrator,Adobe Photoshop,Brochures,Packaging,Exhibition Design,Social Media',
    seoTitle: 'RNZ Group Brochures, Packaging & Brand Design | Charanjit Singh',
    seoDescription: 'Explore Charanjit Singh’s RNZ Group design work across product brochures, fertilizer bags, bottle labels, standees and social media creatives.',
  },
  'ajooba-llc-website': {
    description: 'WordPress and WooCommerce storefront for personalised gifts, greeting cards, labels and stickers in Dubai, supported by SEO and digital marketing.',
    coverImage: '/work/ajooba-llc-live-shot.gif',
    coverAlt: 'Screenshot of the Ajooba LLC online store showing greeting cards, gifts and personalised labels',
    socialImage: '/work/ajooba-llc-live-shot.gif',
    client: 'Ajooba Stationery & Gifts LLC',
    role: 'WordPress and WooCommerce developer · SEO · digital marketing',
    challenge: 'Make a wide catalogue of personalised gifts, cards, labels and stationery easy for Dubai customers to browse and purchase online.',
    solution: 'I built and worked on the WordPress and WooCommerce storefront, organised product and category journeys, and supported the business with SEO, digital marketing and social media work.',
    outcome: 'A live online store that presents Ajooba’s personalised gifts, greeting cards, labels and stickers through category-led shopping paths.',
    tech: 'WordPress,WooCommerce,SEO,E-commerce,Digital Marketing',
    liveUrl: 'https://ajooballc.com/',
    seoTitle: 'Ajooba WordPress & WooCommerce Store | Charanjit Singh',
    seoDescription: 'See Charanjit Singh’s WordPress and WooCommerce work for Ajooba’s personalised gifts store in Dubai, including SEO and digital marketing.',
  },
  'ajooba-ae-opencart': {
    description: 'Custom OpenCart e-commerce work for Ajooba’s gifts and stationery catalogue, with product browsing and shopping flows.',
    client: 'Ajooba Stationery & Gifts LLC',
    role: 'OpenCart developer · e-commerce specialist',
    challenge: 'Adapt an online shopping platform to Ajooba’s varied gift, souvenir and stationery catalogue.',
    solution: 'I customised the OpenCart storefront and its product-shopping experience as part of my wider website work for Ajooba.',
    outcome: 'A tailored e-commerce experience organised around Ajooba’s gift and stationery range.',
    tech: 'OpenCart,PHP,E-commerce,Product Catalogue',
    seoTitle: 'Ajooba OpenCart E-commerce Website | Charanjit Singh',
    seoDescription: 'A custom OpenCart shopping experience built by Charanjit Singh for Ajooba’s gifts and stationery catalogue.',
  },
  'ajooba-gift-item-designs': {
    description: 'Greeting cards, gift graphics, labels and product visuals created for Ajooba’s personalised gifting range.',
    client: 'Ajooba Stationery & Gifts LLC',
    role: 'Graphic and product designer',
    challenge: 'Build a varied but recognisable design language for personalised gifts and occasion-led products.',
    solution: 'I created greeting-card designs, gift graphics, labels and other product visuals used across the Ajooba range and its digital marketing.',
    outcome: 'A growing set of retail-ready creative assets for cards, gifts, labels and promotional use.',
    tech: 'Adobe Illustrator,Adobe Photoshop,Greeting Cards,Product Design,Social Media',
    seoTitle: 'Ajooba Greeting Cards & Gift Graphics | Charanjit Singh',
    seoDescription: 'Explore Charanjit Singh’s graphic design work for Ajooba, including greeting cards, labels, personalised gifts and product visuals.',
  },
  'expocrop-website': {
    description: 'Responsive agriculture website design for Expocrop, shaped around clear brand presentation, mobile usability and search visibility.',
    client: 'Expocrop',
    role: 'Website designer and developer',
    challenge: 'Give a growing agriculture brand a clear digital home that could explain its offer across desktop and mobile screens.',
    solution: 'I designed and developed the website experience, focusing on responsive layouts, straightforward navigation and SEO-aware page structure.',
    outcome: 'A website concept and build aligned with Expocrop’s visual identity and agricultural audience.',
    tech: 'Web Design,Responsive Development,UI/UX,SEO',
    liveUrl: 'https://expocrop.com/',
    seoTitle: 'Expocrop Agriculture Website Design | Charanjit Singh',
    seoDescription: 'Explore Charanjit Singh’s responsive website design and development work for Expocrop, with a focus on mobile UX and search-friendly structure.',
  },
  'expocrop-logo-branding': {
    description: 'A flexible visual identity for Expocrop, including logo variants, colour and typography choices for digital and print use.',
    client: 'Expocrop',
    role: 'Lead brand designer',
    challenge: 'Create a recognisable agriculture identity that could work across a website, packaging, brochures and other brand materials.',
    solution: 'I designed the Expocrop logo system and its supporting visual language, including scalable variants and consistent colour and typography choices.',
    outcome: 'An identity designed for use across digital platforms, printed materials and product communication.',
    tech: 'Adobe Illustrator,Logo Design,Brand Identity,Visual Systems',
    liveUrl: 'https://expocrop.com/',
    seoTitle: 'Expocrop Logo & Agriculture Brand Identity | Charanjit Singh',
    seoDescription: 'See the Expocrop logo and visual identity designed by Charanjit Singh for an agriculture brand across digital and print applications.',
  },
  'expocrop-product-brochures': {
    description: 'Product brochures for Expocrop, designed to make agricultural information clear and visually consistent in print and digital formats.',
    client: 'Expocrop',
    role: 'Brochure and graphic designer',
    challenge: 'Present agricultural product information in a format that is easy to scan and consistent with Expocrop’s identity.',
    solution: 'I designed brochure layouts and product visuals for print and digital distribution, using clear hierarchy and a consistent visual system.',
    outcome: 'A coordinated brochure set for product communication and brand presentation.',
    tech: 'Adobe InDesign,Adobe Illustrator,Brochure Design,Print Design',
    liveUrl: 'https://expocrop.com/',
    seoTitle: 'Expocrop Product Brochure Design | Charanjit Singh',
    seoDescription: 'Explore product brochures designed by Charanjit Singh for Expocrop, combining agricultural information with a consistent visual identity.',
  },
  'forexamg-platform': {
    liveUrl: 'https://www.forexamg.com/',
    seoTitle: 'ForexAMG Laravel Platform Development | Charanjit Singh',
    seoDescription: 'A Laravel development case study covering integrations, SOAP services and automation work completed by Charanjit Singh for ForexAMG.',
  },
  'iapply-unified-search': {
    liveUrl: 'https://iapply.io/',
    seoTitle: 'iApply Unified Search Application | Charanjit Singh',
    seoDescription: 'A full-stack application case study on unified search, login and responsive workflows developed by Charanjit Singh for iApply.',
  },
  'sanskriti-bazaar': {
    description: 'Frontend development, page-speed work and testing for Sanskriti Bazaar’s e-commerce experience, now presented online under the zaimboo name.',
    liveUrl: 'https://sanskritibazaar.in/',
    seoTitle: 'Sanskriti Bazaar E-commerce Frontend Work | Charanjit Singh',
    seoDescription: 'Explore Charanjit Singh’s frontend, performance and testing work for Sanskriti Bazaar’s online shopping experience, now branded zaimboo.',
  },
};

export const projectChannels: Record<string, {label:string;url:string}[]> = {
  'kalia-law-firm': [
    {label:'Instagram',url:'https://www.instagram.com/kalialawfirm/'},
    {label:'Facebook',url:'https://www.facebook.com/people/Kalia-Law-Firm/61554540762945/'},
  ],
  'rnz-group-website': [{label:'LinkedIn',url:'https://www.linkedin.com/company/rnz-group'}],
  'rnz-group-design-portfolio': [{label:'LinkedIn',url:'https://www.linkedin.com/company/rnz-group'}],
  'ajooba-llc-website': [
    {label:'Instagram',url:'https://www.instagram.com/ajoobadubai/'},
    {label:'Facebook',url:'https://www.facebook.com/ajoobadubai/'},
  ],
  'ajooba-gift-item-designs': [
    {label:'Instagram',url:'https://www.instagram.com/ajoobadubai/'},
    {label:'Facebook',url:'https://www.facebook.com/ajoobadubai/'},
  ],
};
