// Invoked by check-platform.cjs against its isolated server and data directory.
const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');
module.exports=async({request,check,base,folder,password,authSecret,getCookie,setCookie})=>{
 check((await request('/api/admin/managed-sites/reminders','POST',{action:'run'})).status===401,'renewal email controls require authentication');
 check((await request('/api/admin/managed-sites/reminders','POST',{action:'run'},true,'https://untrusted.test')).status===403,'cross-origin renewal sends rejected');
 const managed={clientName:'Test client',label:'Renewal charge test',url:'https://example.com',domainProvider:'Domain provider',domainRenewal:'2026-10-22',serverProvider:'Host',serverRenewal:'2026-10-30',domainCharge:120.10,serverCharge:300.20,contactEmail:'',notes:'Private AED charge',active:true};
 const created=await request('/api/admin/managed-sites','POST',managed,true);check(created.status===201,'admin saves renewal charges');const managedRecord=(await created.json()).site;
 const managedList=await(await request('/api/admin/managed-sites','GET',undefined,true)).json();const found=managedList.sites.find(x=>x.id===managedRecord.id);check(found?.domainCharge===120.10&&found?.serverCharge===300.20,'renewal charges persist on reload');
 check((await request('/api/admin/managed-sites','POST',{...managed,id:managedRecord.id,domainCharge:-1},true)).status===400,'negative renewal charge rejected');
 check((await request('/api/admin/managed-sites','POST',{...managed,id:managedRecord.id,domainCharge:1.001},true)).status===400,'fractional cents rejected');
 await request('/api/admin/managed-sites/'+managedRecord.id,'DELETE',undefined,true);
 let r=await request('/api/admin/studio');check(r.status===401,'studio data requires authentication');
 const data=await(await request('/api/admin/studio','GET',undefined,true)).json();
 const content={...data.content,name:'Studio content test',bio:'A profile edited through the studio content manager.',seoTitle:'Studio search title',testimonials:[{name:'Unpublished person',role:'Test only',quote:'This private test quote must not appear publicly.',approved:false}]};
 check((await request('/api/admin/studio','POST',{action:'content',content},true,'https://untrusted.test')).status===403,'cross-origin content editing rejected');
 check((await request('/api/admin/studio','POST',{action:'content',content:{...content,cvUrl:'javascript:alert(1)'}},true)).status===400,'unsafe site content URL rejected');
 check((await request('/api/admin/studio','POST',{action:'content',content},true)).status===200,'site content can be published');
 const home=await(await request('/')).text();check(home.includes(content.name)&&home.includes(content.bio)&&home.includes(content.seoTitle),'edited profile and SEO render publicly');
 check(!home.includes('Unpublished person')&&!home.includes('<blockquote'),'unapproved testimonials are excluded from public content');
 check((await(await request('/resume')).text()).includes(content.bio),'resume follows editable profile');
 check((await request('/api/admin/studio','POST',{action:'draft',key:'site',data:{...content,name:'Unpublished draft'}},true)).status===200,'site draft autosave works');
 check(!(await(await request('/')).text()).includes('Unpublished draft'),'autosave does not publish a draft');
 const history=await(await request('/api/admin/studio','GET',undefined,true)).json();const previous=history.revisions.find(r=>r.kind==='site');
 check(!!previous,'site revision preserved');
 check((await request('/api/admin/studio','POST',{action:'restore',id:previous.id},true)).status===200,'site revision can be restored');
 const projects=await(await request('/api/projects')).json();const p=projects[0];
 const rich={...p,results:'Verified test result',videoUrl:'https://example.com/demo.mp4',documentUrl:'https://example.com/story.pdf',seoTitle:'Project search preview',seoDescription:'Project search description',socialImage:p.coverImage};
 check((await request('/api/projects/'+p.id,'PUT',rich,true)).status===200,'rich case study fields save');
 const html=await(await request('/work/'+p.slug)).text();check(html.includes(rich.results)&&html.includes(rich.videoUrl)&&html.includes(rich.documentUrl)&&html.includes(rich.seoTitle)&&html.includes('project='+encodeURIComponent(p.title)),'case study shows results, media, search title and project inquiry link');
 await request('/api/projects/'+p.id,'DELETE',undefined,true);
 check((await request('/work/'+p.slug)).status===404,'trashed project is hidden');
 const trash=await(await request('/api/admin/studio','GET',undefined,true)).json();check(trash.trash.some(t=>t.id===p.id),'deleted project is recoverable in trash');
 check((await request('/api/admin/studio','POST',{action:'restoreTrash',id:p.id},true)).status===200,'trash restore succeeds');
 check((await request('/work/'+p.slug)).status===404,'restoration is private until republished');
 await request('/api/projects/'+p.id,'PUT',p,true);
 const authHeaders={Origin:base,Cookie:getCookie()};const file=new FormData();file.append('file',new Blob(['%PDF-1.4\n% isolated test document\n%%EOF'],{type:'application/pdf'}),'sample.pdf');
 r=await fetch(base+'/api/admin/upload',{method:'POST',headers:authHeaders,body:file});check(r.status===200,'PDF upload accepted');const pdf=await r.json();check((await fetch(base+pdf.url)).headers.get('content-type')==='application/pdf','PDF served with correct type');
 const library=await(await request('/api/admin/studio','GET',undefined,true)).json();const media=library.media.find(m=>m.url===pdf.url);check(!!media,'upload registered in reusable media library');
 check((await request('/api/admin/studio','POST',{action:'media',id:media.id,name:'Case study',alt:'Test PDF',folder:'Agriculture'},true)).status===200,'media metadata and project folder save');
 const inquiry={name:'Studio inquiry',email:'studio@example.test',company:'',service:'Development',budget:'Exploring options',message:'I would like to discuss a project like this example.',consent:true,website:'',requestId:crypto.randomUUID(),project:p.title,source:'/contact'};
 r=await request('/api/inquiries','POST',inquiry);const received=await r.json();check(r.status===201,'project-specific inquiry saved');
 check((await request('/api/admin/inquiries/'+received.id,'PATCH',{status:'proposal sent',notes:'Proposal review',followUp:'2026-10-01'},true)).status===200,'pipeline stage and follow-up date save');
 const inbox=await(await request('/api/admin','GET',undefined,true)).json();check(inbox.inquiries.some(i=>i.id===received.id&&i.project===p.title&&i.followUp==='2026-10-01'),'project and follow-up visible in inbox');
 check((await request('/api/analytics','POST',{path:'/work/'+p.slug})).status===204,'aggregate page view recorded');
 check((await request('/api/analytics','POST',{path:'/admin'})).status===400,'admin pages excluded from analytics');
 const analytics=await(await request('/api/admin/studio','GET',undefined,true)).json();check(Object.entries(analytics.analytics).some(([k,v])=>k.endsWith('/work/'+p.slug)&&v.views>=1&&v.inquiries>=1),'analytics shows project views and attributed inquiry');
 check((await request('/api/auth/recovery','POST',{action:'request',email:'test@example.test'})).status===503,'unconfigured Hostinger SMTP recovery is reported honestly');
 check((await request('/api/admin/smtp-test','POST',{},true)).status===503,'unconfigured Hostinger SMTP test is reported honestly');
 const before=getCookie();const security=await(await request('/api/admin/security','GET',undefined,true)).json();check(security.sessions.length>=1,'active sessions available');
 r=await request('/api/admin/security','POST',{action:'begin',password:'incorrect'},true);check(r.status===400,'MFA enrollment requires current password');
 r=await request('/api/admin/security','POST',{action:'begin',password},true);check(r.status===200,'MFA enrollment generates a key');const enrollment=await r.json();
 const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of enrollment.secret)bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(x=>parseInt(x,2)));const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=crypto.createHmac('sha1',key).update(counter).digest();const offset=digest[19]&15;const code=String((digest.readUInt32BE(offset)&0x7fffffff)%1000000).padStart(6,'0');
 check((await request('/api/admin/security','POST',{action:'confirm',password,code:'invalid'},true)).status===400,'MFA requires proof from authenticator');
 r=await request('/api/admin/security','POST',{action:'confirm',password,code},true);check(r.status===200,'valid authenticator code enables MFA');const enabled=await r.json();check(enabled.codes.length===8,'single-use recovery codes issued');
 check((await request('/api/admin','GET',undefined,true)).status===401,'enabling MFA revokes pre-enrollment sessions');
 check((await request('/api/auth/login','POST',{email:'test@example.test',password})).status===401,'password alone cannot bypass MFA');
 r=await request('/api/auth/login','POST',{email:'test@example.test',password,code:enabled.codes[0]});check(r.status===200,'recovery code supports admin sign-in');setCookie(r.headers.get('set-cookie').split(';')[0]);
 check((await request('/api/auth/login','POST',{email:'test@example.test',password,code:enabled.codes[0]})).status===401,'recovery code cannot be reused');
 const filePath=path.join(folder,'platform.json');let stored=JSON.parse(fs.readFileSync(filePath,'utf8'));check(!JSON.stringify(stored.security).includes(enrollment.secret),'authenticator key is encrypted at rest');
 const resetCode='12345678',newerCode='87654321';const resetHash=value=>crypto.createHmac('sha256',crypto.createHash('sha256').update(authSecret).digest()).update('admin-password-reset:'+value).digest('hex');stored.security.resets=[{hash:resetHash(resetCode),expires:Date.now()+60000,attempts:0},{hash:resetHash(newerCode),expires:Date.now()+60000,attempts:0}];fs.writeFileSync(filePath,JSON.stringify(stored));
 const nextPassword='A-long-random-test-'+crypto.randomBytes(12).toString('hex');check((await request('/api/auth/recovery','POST',{action:'reset',code:'00000000',password:nextPassword})).status===400,'incorrect email code is rejected');r=await request('/api/auth/recovery','POST',{action:'reset',code:resetCode,password:nextPassword});check(r.status===200,'earlier email code still works after a newer code is sent');
 check((await request('/api/admin','GET',undefined,true)).status===401,'password reset revokes existing sessions');
 check((await request('/api/auth/recovery','POST',{action:'reset',code:resetCode,password:nextPassword})).status===400,'reset email code cannot be reused');
 check((await request('/api/auth/login','POST',{email:'test@example.test',password:nextPassword})).status===401,'password reset retains MFA protection');
 r=await request('/api/auth/login','POST',{email:'test@example.test',password:nextPassword,code:enabled.codes[1]});check(r.status===200,'new password plus recovery code signs in');setCookie(r.headers.get('set-cookie').split(';')[0]);
 const sessions=await(await request('/api/admin/security','GET',undefined,true)).json();await request('/api/admin/security','POST',{action:'revoke',id:sessions.sessions[0].id},true);check((await request('/api/admin','GET',undefined,true)).status===401,'session revocation immediately blocks protected APIs');setCookie(before);
};
